"""Regression tests for QMCPACK scalar block summaries."""

from __future__ import annotations

from pathlib import Path

import pytest

from chemtools.mcp.tools.qmcpack import (
    _handle_analyze_qmcpack_dmc_input_series,
    _handle_analyze_qmcpack_dmc_series,
    _handle_check_qmcpack_vmc_energy_gate,
    _handle_compare_qmcpack_tmove_locality_shift,
    _handle_compare_qmcpack_tmove_locality_shift_from_input,
    _handle_inspect_qmcpack_determinant_vmc_offsets,
    _handle_inspect_qmcpack_dmc_population,
    _handle_inspect_qmcpack_dmc_population_from_input,
    _handle_inspect_qmcpack_scalar,
)
from chemtools.programs.qmcpack.dmc import (
    analyze_dmc_input_series,
    analyze_dmc_series,
    compare_tmove_locality_shift,
    compare_tmove_locality_shift_from_input,
    inspect_dmc_population,
    inspect_dmc_population_from_input,
)
from chemtools.programs.qmcpack.gates import (
    check_vmc_energy_gate,
    inspect_determinant_only_vmc_offsets,
)
from chemtools.programs.qmcpack.scalar import parse_scalar_file, parse_scalar_text


SCALAR_DATA = """\
# Generated by QMCPACK
QMCPACK scalar output
# index LocalEnergy LocalEnergy_sq BlockWeight AcceptRatio
0 -10.0 101.0 20.0 0.25
1 -12.0 145.0 10.0 0.50
2 -11.0 122.0 30.0 0.75
"""


def test_parse_scalar_text_summarizes_observed_estimators():
    parsed = parse_scalar_text(SCALAR_DATA)

    assert parsed == {
        "schema_version": "chemtools.qmcpack-scalar/1",
        "path": None,
        "filename_identity": None,
        "columns": [
            "index",
            "LocalEnergy",
            "LocalEnergy_sq",
            "BlockWeight",
            "AcceptRatio",
        ],
        "row_count": 3,
        "first_block": 0,
        "last_block": 2,
        "block_index_sequence": {
            "status": "contiguous",
            "gap_transition_count": 0,
            "nonincreasing_transition_count": 0,
        },
        "invalid_row_count": 0,
        "invalid_row_reasons": {
            "malformed": 0,
            "non_finite": 0,
            "non_integral_index": 0,
        },
        "truncated": False,
        "estimators": {
            "LocalEnergy": {
                "mean": -11.0,
                "sample_stdev": 1.0,
                "minimum": -12.0,
                "maximum": -10.0,
                "last": -11.0,
                "weighted_mean": -10.833333333333334,
            },
            "LocalEnergy_sq": {
                "mean": 122.66666666666667,
                "sample_stdev": 22.00757445365875,
                "minimum": 101.0,
                "maximum": 145.0,
                "last": 122.0,
            },
            "BlockWeight": {
                "mean": 20.0,
                "sample_stdev": 10.0,
                "minimum": 10.0,
                "maximum": 30.0,
                "last": 30.0,
            },
            "AcceptRatio": {
                "mean": 0.5,
                "sample_stdev": 0.25,
                "minimum": 0.25,
                "maximum": 0.75,
                "last": 0.75,
            },
        },
        "local_energy_second_moment": {
            "status": "consistent",
            "block_count": 3,
            "minimum_second_moment_minus_mean_squared": 1.0,
            "negative_bound_violation_count": 0,
            "relative_tolerance": 1e-12,
            "scope_limit": (
                "This checks the recorded per-block second-moment bound; it does not "
                "estimate statistical uncertainty or convergence."
            ),
        },
        "acceptance_ratio_bounds": {
            "status": "within_bounds",
            "block_count": 3,
            "minimum": 0.25,
            "maximum": 0.75,
            "below_zero_count": 0,
            "above_one_count": 0,
            "bound_tolerance": 1e-12,
            "scope_limit": (
                "This checks the recorded acceptance-ratio bounds; it does not "
                "recommend an acceptance-rate target."
            ),
        },
        "block_weight_quality": {
            "status": "positive",
            "block_count": 3,
            "minimum": 10.0,
            "maximum": 30.0,
            "zero_count": 0,
            "negative_count": 0,
            "scope_limit": (
                "This reports recorded block-weight sign only; it does not change "
                "unweighted scalar analyses."
            ),
        },
        "energy_component_balance": {
            "status": "not_available",
            "reason": "LocalEnergy, Kinetic, and LocalPotential columns are required.",
        },
    }


def test_parse_scalar_file_reports_invalid_rows_and_mcp_handler(tmp_path):
    path = tmp_path / "O.s000.scalar.dat"
    path.write_text(SCALAR_DATA + "bad row\n3.5 -10.0 100.0 20.0 0.25\n", encoding="utf-8")

    parsed = parse_scalar_file(path)

    assert parsed["path"] == str(path.resolve())
    assert parsed["filename_identity"] == {
        "status": "recognized",
        "project_id": "O",
        "series_index": 0,
        "scope_limit": (
            "Filename identity does not establish the source QMC input block or "
            "its controls."
        ),
    }
    assert parsed["invalid_row_count"] == 2
    assert parsed["invalid_row_reasons"] == {
        "malformed": 1,
        "non_finite": 0,
        "non_integral_index": 1,
    }
    assert _handle_inspect_qmcpack_scalar({"scalar_file": str(path)}) == parsed


def test_parse_scalar_file_marks_an_unrecognized_filename(tmp_path):
    path = tmp_path / "scalar.dat"
    path.write_text(SCALAR_DATA, encoding="utf-8")

    parsed = parse_scalar_file(path)

    assert parsed["filename_identity"] == {
        "status": "unrecognized",
        "filename": "scalar.dat",
        "scope_limit": (
            "The scalar filename does not match the supported project.sNNN.scalar.dat "
            "convention."
        ),
    }


def test_parse_scalar_text_requires_header_and_valid_rows():
    with pytest.raises(ValueError, match="no '#' column header"):
        parse_scalar_text("0 -10.0\n")
    with pytest.raises(ValueError, match="contains no valid block rows"):
        parse_scalar_text("# index LocalEnergy\ninvalid\n")


def test_parse_scalar_text_reports_nonfinite_rows():
    parsed = parse_scalar_text("""\
# index LocalEnergy
0 -nan
1 -10.0
""")

    assert parsed["invalid_row_count"] == 1
    assert parsed["invalid_row_reasons"] == {
        "malformed": 0,
        "non_finite": 1,
        "non_integral_index": 0,
    }

    with pytest.raises(ValueError, match="Rejected: 1 non-finite row\\(s\\)"):
        parse_scalar_text("# index LocalEnergy\n0 nan\n")


def test_parse_scalar_text_preserves_block_index_discontinuities():
    parsed = parse_scalar_text("""\
# index LocalEnergy
2 -10.0
4 -9.9
3 -9.8
""")

    assert parsed["block_index_sequence"] == {
        "status": "noncontiguous",
        "gap_transition_count": 1,
        "nonincreasing_transition_count": 1,
    }


def test_parse_scalar_text_checks_local_energy_second_moment_bound():
    inspected = parse_scalar_text("""\
# index LocalEnergy LocalEnergy_sq
0 -10.0 99.0
1 -9.0 81.0
""")

    assert inspected["local_energy_second_moment"] == {
        "status": "inconsistent",
        "block_count": 2,
        "minimum_second_moment_minus_mean_squared": -1.0,
        "negative_bound_violation_count": 1,
        "relative_tolerance": 1e-12,
        "scope_limit": (
            "This checks the recorded per-block second-moment bound; it does not "
            "estimate statistical uncertainty or convergence."
        ),
    }
    missing = parse_scalar_text("# index LocalEnergy\n0 -10.0\n")
    assert missing["local_energy_second_moment"] == {
        "status": "not_available",
        "reason": "LocalEnergy and LocalEnergy_sq columns are required.",
    }


def test_parse_scalar_text_checks_acceptance_ratio_bounds():
    inspected = parse_scalar_text("""\
# index LocalEnergy AcceptRatio
0 -10.0 -0.01
1 -9.9 1.1
""")

    assert inspected["acceptance_ratio_bounds"] == {
        "status": "out_of_bounds",
        "block_count": 2,
        "minimum": -0.01,
        "maximum": 1.1,
        "below_zero_count": 1,
        "above_one_count": 1,
        "bound_tolerance": 1e-12,
        "scope_limit": (
            "This checks the recorded acceptance-ratio bounds; it does not "
            "recommend an acceptance-rate target."
        ),
    }
    missing = parse_scalar_text("# index LocalEnergy\n0 -10.0\n")
    assert missing["acceptance_ratio_bounds"] == {
        "status": "not_available",
        "reason": "An AcceptRatio column is required.",
    }


def test_parse_scalar_text_checks_block_weight_quality():
    inspected = parse_scalar_text("""\
# index LocalEnergy BlockWeight
0 -10.0 0
1 -9.9 -2
""")

    assert inspected["estimators"]["LocalEnergy"]["weighted_mean"] is None
    assert inspected["block_weight_quality"] == {
        "status": "nonpositive",
        "block_count": 2,
        "minimum": -2.0,
        "maximum": 0.0,
        "zero_count": 1,
        "negative_count": 1,
        "scope_limit": (
            "This reports recorded block-weight sign only; it does not change "
            "unweighted scalar analyses."
        ),
    }
    missing = parse_scalar_text("# index LocalEnergy\n0 -10.0\n")
    assert missing["block_weight_quality"] == {
        "status": "not_available",
        "reason": "A BlockWeight column is required.",
    }


def test_parse_scalar_text_checks_energy_component_balance():
    inspected = parse_scalar_text("""\
# index LocalEnergy Kinetic LocalPotential
0 -10.0 2.0 -12.0
1 -9.9 2.1 -12.5
""")

    assert inspected["energy_component_balance"] == {
        "status": "unbalanced",
        "block_count": 2,
        "minimum_residual": 0.0,
        "maximum_residual": 0.5,
        "maximum_absolute_residual": 0.5,
        "violation_count": 1,
        "relative_tolerance": 1e-9,
        "scope_limit": (
            "This checks the reported LocalEnergy, Kinetic, and LocalPotential "
            "balance only; it does not establish Hamiltonian completeness."
        ),
    }
    missing = parse_scalar_text("# index LocalEnergy\n0 -10.0\n")
    assert missing["energy_component_balance"] == {
        "status": "not_available",
        "reason": "LocalEnergy, Kinetic, and LocalPotential columns are required.",
    }


def test_analyze_dmc_series_reblocks_and_fits_tmove_points(tmp_path):
    slow = tmp_path / "slow.scalar.dat"
    fast = tmp_path / "fast.scalar.dat"
    slow.write_text(
        "# index LocalEnergy\n0 -10.1\n1 -9.9\n2 -9.9\n3 -9.7\n",
        encoding="utf-8",
    )
    fast.write_text(
        "# index LocalEnergy\n0 -10.3\n1 -10.1\n2 -10.1\n3 -9.9\n",
        encoding="utf-8",
    )
    arguments = {
        "runs": [
            {"scalar_file": str(slow), "timestep": 0.1, "nonlocalmoves": True, "target_walkers": 100, "potential_label": "Ce-sECP"},
            {"scalar_file": str(fast), "timestep": 0.05, "nonlocalmoves": True, "target_walkers": 100, "potential_label": "Ce-sECP"},
        ],
        "discard_fraction": 0,
        "reblock_count": 2,
    }

    parsed = analyze_dmc_series(**arguments)

    assert [point["local_energy_mean"] for point in parsed["points"]] == [-9.9, -10.1]
    assert [point["local_energy_standard_error"] for point in parsed["points"]] == [
        pytest.approx(0.1),
        pytest.approx(0.1),
    ]
    assert parsed["fits"]["tmove"] == {
        "status": "fit",
        "point_count": 2,
        "timesteps": [0.05, 0.1],
        "zero_timestep_energy": pytest.approx(-10.3),
        "zero_timestep_standard_error": pytest.approx(0.22360679774997896),
        "slope": pytest.approx(4.0),
        "slope_standard_error": pytest.approx(2.8284271247461903),
        "chi_squared": pytest.approx(0.0),
        "degrees_of_freedom": 0,
        "reduced_chi_squared": None,
    }
    assert parsed["potential_identity"] == {
        "status": "uniform",
        "potential_label": "Ce-sECP",
    }
    assert parsed["warnings"] == []
    assert _handle_analyze_qmcpack_dmc_series(arguments) == parsed

    unlabelled = analyze_dmc_series(
        [
            {key: value for key, value in run.items() if key != "potential_label"}
            for run in arguments["runs"]
        ],
        discard_fraction=0,
        reblock_count=2,
    )
    assert unlabelled["potential_identity"] == {
        "status": "not_assessed",
        "reason": "potential_label was not supplied for every run",
        "missing_scalar_files": [str(slow), str(fast)],
    }


def test_analyze_dmc_input_series_binds_controls_from_selected_input_blocks(tmp_path):
    input_path = tmp_path / "campaign.xml"
    input_path.write_text("""\
<simulation>
  <qmc method="vmc"/>
  <qmc method="dmc">
    <parameter name="timestep">0.1</parameter>
    <parameter name="nonlocalmoves">yes</parameter>
    <parameter name="targetWalkers">100</parameter>
  </qmc>
  <qmc method="dmc">
    <parameter name="timestep">0.05</parameter>
    <parameter name="nonlocalmoves">yes</parameter>
    <parameter name="total_walkers">100</parameter>
  </qmc>
</simulation>
""", encoding="utf-8")
    slow = tmp_path / "slow.scalar.dat"
    fast = tmp_path / "fast.scalar.dat"
    slow.write_text("# index LocalEnergy\n0 -10.1\n1 -9.9\n", encoding="utf-8")
    fast.write_text("# index LocalEnergy\n0 -10.2\n1 -10.0\n", encoding="utf-8")
    arguments = {
        "qmcpack_input": str(input_path),
        "runs": [
            {"scalar_file": str(slow), "qmc_block_index": 1, "potential_label": "Ce-sECP"},
            {"scalar_file": str(fast), "qmc_block_index": 2, "potential_label": "Ce-sECP"},
        ],
        "discard_fraction": 0,
        "reblock_count": 2,
    }

    inspected = analyze_dmc_input_series(**arguments)

    assert inspected["schema_version"] == "chemtools.qmcpack-dmc-input-series/1"
    assert inspected["qmcpack_input"] == str(input_path.resolve())
    assert inspected["bindings"] == [
        {
            "scalar_file": str(slow.resolve()),
            "qmc_block_index": 1,
            "dmc_input": {
                "qmc_block_index": 1,
                "timestep": 0.1,
                "blocks": None,
                "target_walkers": 100,
                "nonlocalmoves": True,
            },
            "scalar_filename_project": {
                "status": "not_checked",
                "reason": "The QMCPACK input has no project id.",
            },
        },
        {
            "scalar_file": str(fast.resolve()),
            "qmc_block_index": 2,
            "dmc_input": {
                "qmc_block_index": 2,
                "timestep": 0.05,
                "blocks": None,
                "target_walkers": 100,
                "nonlocalmoves": True,
            },
            "scalar_filename_project": {
                "status": "not_checked",
                "reason": "The QMCPACK input has no project id.",
            },
        },
    ]
    assert [point["timestep"] for point in inspected["analysis"]["points"]] == [0.1, 0.05]
    assert inspected["analysis"]["potential_identity"]["status"] == "uniform"
    assert _handle_analyze_qmcpack_dmc_input_series(arguments) == inspected

    with pytest.raises(ValueError, match="does not select a DMC block"):
        analyze_dmc_input_series(
            input_path,
            [{"scalar_file": str(slow), "qmc_block_index": 0}],
        )


def test_input_bound_dmc_series_reports_scalar_filename_project_mismatch(tmp_path):
    input_path = tmp_path / "campaign.xml"
    input_path.write_text("""\
<simulation>
  <project id="Ce_dmc" series="0"/>
  <qmc method="dmc">
    <parameter name="timestep">0.1</parameter>
    <parameter name="nonlocalmoves">yes</parameter>
  </qmc>
</simulation>
""", encoding="utf-8")
    scalar = tmp_path / "Pr_dmc.s000.scalar.dat"
    scalar.write_text("# index LocalEnergy\n0 -10.1\n1 -9.9\n", encoding="utf-8")

    inspected = analyze_dmc_input_series(
        input_path,
        [{"scalar_file": str(scalar), "qmc_block_index": 0}],
        discard_fraction=0,
        reblock_count=2,
    )

    assert inspected["bindings"][0]["scalar_filename_project"] == {
        "status": "mismatch",
        "input_project_id": "Ce_dmc",
        "scalar_project_id": "Pr_dmc",
        "scope_limit": (
            "This compares the filename project label only; it does not establish "
            "the source QMC block or its controls."
        ),
    }
    assert inspected["binding_warnings"] == [{
        "code": "scalar_filename_project_mismatch",
        "scalar_file": str(scalar.resolve()),
        "input_project_id": "Ce_dmc",
        "scalar_project_id": "Pr_dmc",
        "message": (
            "The scalar filename project label does not match the QMCPACK input "
            "project ID."
        ),
    }]


def test_input_bound_dmc_analysis_refuses_included_block_selection(tmp_path):
    input_path = tmp_path / "campaign.xml"
    input_path.write_text("""\
<simulation><include href="dmc.xml"/></simulation>
""", encoding="utf-8")
    (tmp_path / "dmc.xml").write_text("""\
<simulation><qmc method="dmc"><parameter name="timestep">0.01</parameter></qmc></simulation>
""", encoding="utf-8")

    with pytest.raises(ValueError, match="primary QMCPACK XML.*does not merge included XML"):
        analyze_dmc_input_series(
            input_path,
            [{"scalar_file": str(tmp_path / "dmc.scalar.dat"), "qmc_block_index": 0}],
        )


def test_analyze_dmc_series_separates_tmove_and_reports_input_errors(tmp_path):
    scalar = tmp_path / "dmc.scalar.dat"
    no_tmove_scalar = tmp_path / "no-tmove.scalar.dat"
    scalar_text = "# index LocalEnergy BlockWeight\n0 -10.0 10\n1 -9.8 11\n3 -10.2 12\n2 -10.0 13\nbad row\n"
    scalar.write_text(scalar_text, encoding="utf-8")
    no_tmove_scalar.write_text(scalar_text, encoding="utf-8")

    parsed = analyze_dmc_series(
        [
            {"scalar_file": str(scalar), "timestep": 0.1, "nonlocalmoves": True, "target_walkers": 100, "potential_label": "Ce-sECP"},
            {"scalar_file": str(no_tmove_scalar), "timestep": 0.1, "nonlocalmoves": False, "target_walkers": 200, "potential_label": "Ce-ONCV"},
        ],
        discard_fraction=0,
        reblock_count=2,
    )

    assert parsed["fits"]["tmove"]["status"] == "not_fit"
    assert parsed["fits"]["no_tmove"]["status"] == "not_fit"
    assert parsed["potential_identity"] == {
        "status": "mixed",
        "potential_labels": ["Ce-ONCV", "Ce-sECP"],
    }
    assert parsed["warnings"] == [
        "Runs use different target_walkers values; inspect population-control comparability.",
        "T-move and no-T-move points were fit separately and must not be combined.",
        "Runs declare multiple potential_label values; do not combine different potentials in one time-step fit.",
        "At least one run has varying BlockWeight; LocalEnergy is reblocked as recorded block values.",
        "At least one scalar file contains malformed rows that were excluded.",
        "At least one scalar file has gaps or nonincreasing block indices.",
    ]
    with pytest.raises(ValueError, match="positive finite timestep"):
        analyze_dmc_series([
            {"scalar_file": str(scalar), "timestep": 0, "nonlocalmoves": True},
        ])


def test_analyze_dmc_series_ignores_discarded_block_weight_variation(tmp_path):
    scalar = tmp_path / "dmc.scalar.dat"
    scalar.write_text("""\
# index LocalEnergy BlockWeight
0 -10.3 1
1 -10.1 2
2 -9.9 2
3 -9.7 2
""", encoding="utf-8")

    parsed = analyze_dmc_series(
        [{"scalar_file": str(scalar), "timestep": 0.01, "nonlocalmoves": True}],
        discard_fraction=0.25,
        reblock_count=2,
    )

    assert parsed["points"][0]["block_weights_constant"] is True
    assert not any("varying BlockWeight" in warning for warning in parsed["warnings"])


def test_dmc_series_preserves_nonfinite_scalar_evidence(tmp_path):
    slow = tmp_path / "slow.scalar.dat"
    fast = tmp_path / "fast.scalar.dat"
    for path, values in ((slow, "-10.1 -9.9"), (fast, "-10.3 -10.1")):
        path.write_text(
            f"# index LocalEnergy\n0 nan\n1 {values.split()[0]}\n2 {values.split()[1]}\n",
            encoding="utf-8",
        )

    inspected = analyze_dmc_series(
        [
            {"scalar_file": str(slow), "timestep": 0.1, "nonlocalmoves": True},
            {"scalar_file": str(fast), "timestep": 0.05, "nonlocalmoves": True},
        ],
        discard_fraction=0,
        reblock_count=2,
    )

    assert [point["invalid_row_reasons"] for point in inspected["points"]] == [
        {"malformed": 0, "non_finite": 1, "non_integral_index": 0},
        {"malformed": 0, "non_finite": 1, "non_integral_index": 0},
    ]
    assert inspected["warnings"] == [
        "Potential identity was not supplied for every run; do not treat the "
        "time-step fit as same-potential evidence.",
        "At least one scalar file contains non-finite rows that were excluded.",
    ]


def test_dmc_analysis_rejects_reused_scalar_files(tmp_path):
    scalar = tmp_path / "dmc.scalar.dat"
    scalar.write_text("# index LocalEnergy\n0 -10.1\n1 -9.9\n", encoding="utf-8")
    run = {"scalar_file": str(scalar), "timestep": 0.01, "nonlocalmoves": True}

    with pytest.raises(ValueError, match="DMC series requires distinct scalar_file"):
        analyze_dmc_series([run, {**run, "timestep": 0.005}])
    with pytest.raises(ValueError, match="T-move locality shift requires distinct scalar_file"):
        compare_tmove_locality_shift(run, run)


def test_dmc_series_warns_about_inconsistent_local_energy_second_moment(tmp_path):
    slow = tmp_path / "slow.scalar.dat"
    fast = tmp_path / "fast.scalar.dat"
    slow.write_text(
        "# index LocalEnergy LocalEnergy_sq\n0 -10.1 101\n1 -9.9 97\n",
        encoding="utf-8",
    )
    fast.write_text(
        "# index LocalEnergy LocalEnergy_sq\n0 -10.3 105\n1 -10.1 102\n",
        encoding="utf-8",
    )

    inspected = analyze_dmc_series(
        [
            {"scalar_file": str(slow), "timestep": 0.1, "nonlocalmoves": True},
            {"scalar_file": str(fast), "timestep": 0.05, "nonlocalmoves": True},
        ],
        discard_fraction=0,
        reblock_count=2,
    )

    assert inspected["points"][0]["local_energy_second_moment"]["status"] == "inconsistent"
    assert inspected["warnings"] == [
        "Potential identity was not supplied for every run; do not treat the "
        "time-step fit as same-potential evidence.",
        "At least one scalar file has LocalEnergy_sq below the LocalEnergy "
        "second-moment bound.",
    ]


def test_dmc_series_warns_about_out_of_bounds_acceptance_ratio(tmp_path):
    slow = tmp_path / "slow.scalar.dat"
    fast = tmp_path / "fast.scalar.dat"
    slow.write_text(
        "# index LocalEnergy AcceptRatio\n0 -10.1 1.1\n1 -9.9 0.9\n",
        encoding="utf-8",
    )
    fast.write_text(
        "# index LocalEnergy AcceptRatio\n0 -10.3 0.9\n1 -10.1 0.9\n",
        encoding="utf-8",
    )

    inspected = analyze_dmc_series(
        [
            {"scalar_file": str(slow), "timestep": 0.1, "nonlocalmoves": True},
            {"scalar_file": str(fast), "timestep": 0.05, "nonlocalmoves": True},
        ],
        discard_fraction=0,
        reblock_count=2,
    )

    assert inspected["points"][0]["acceptance_ratio_bounds"]["status"] == "out_of_bounds"
    assert inspected["warnings"] == [
        "Potential identity was not supplied for every run; do not treat the "
        "time-step fit as same-potential evidence.",
        "At least one scalar file has AcceptRatio values outside [0, 1].",
    ]


def test_dmc_series_warns_about_nonpositive_block_weight(tmp_path):
    slow = tmp_path / "slow.scalar.dat"
    fast = tmp_path / "fast.scalar.dat"
    slow.write_text(
        "# index LocalEnergy BlockWeight\n0 -10.1 0\n1 -9.9 1\n",
        encoding="utf-8",
    )
    fast.write_text(
        "# index LocalEnergy BlockWeight\n0 -10.3 1\n1 -10.1 1\n",
        encoding="utf-8",
    )

    inspected = analyze_dmc_series(
        [
            {"scalar_file": str(slow), "timestep": 0.1, "nonlocalmoves": True},
            {"scalar_file": str(fast), "timestep": 0.05, "nonlocalmoves": True},
        ],
        discard_fraction=0,
        reblock_count=2,
    )

    assert inspected["points"][0]["block_weight_quality"]["status"] == "nonpositive"
    assert inspected["warnings"] == [
        "Potential identity was not supplied for every run; do not treat the "
        "time-step fit as same-potential evidence.",
        "At least one run has varying BlockWeight; LocalEnergy is reblocked as "
        "recorded block values.",
        "At least one scalar file has non-positive BlockWeight values; its "
        "weighted LocalEnergy mean is unavailable.",
    ]


def test_dmc_series_warns_about_unbalanced_energy_components(tmp_path):
    slow = tmp_path / "slow.scalar.dat"
    fast = tmp_path / "fast.scalar.dat"
    slow.write_text(
        "# index LocalEnergy Kinetic LocalPotential\n0 -10.1 2 -12\n1 -9.9 2 -12\n",
        encoding="utf-8",
    )
    fast.write_text(
        "# index LocalEnergy Kinetic LocalPotential\n0 -10.3 2 -12.3\n1 -10.1 2 -12.1\n",
        encoding="utf-8",
    )

    inspected = analyze_dmc_series(
        [
            {"scalar_file": str(slow), "timestep": 0.1, "nonlocalmoves": True},
            {"scalar_file": str(fast), "timestep": 0.05, "nonlocalmoves": True},
        ],
        discard_fraction=0,
        reblock_count=2,
    )

    assert inspected["points"][0]["energy_component_balance"]["status"] == "unbalanced"
    assert inspected["warnings"] == [
        "Potential identity was not supplied for every run; do not treat the "
        "time-step fit as same-potential evidence.",
        "At least one scalar file has an unbalanced LocalEnergy, Kinetic, "
        "and LocalPotential record.",
    ]


def test_analyze_dmc_series_withholds_fit_for_mixed_potentials(tmp_path):
    slow = tmp_path / "slow.scalar.dat"
    fast = tmp_path / "fast.scalar.dat"
    for path, energy in ((slow, -9.9), (fast, -10.1)):
        path.write_text(
            f"# index LocalEnergy\n0 {energy - 0.1}\n1 {energy + 0.1}\n",
            encoding="utf-8",
        )

    parsed = analyze_dmc_series(
        [
            {
                "scalar_file": str(slow),
                "timestep": 0.1,
                "nonlocalmoves": True,
                "potential_label": "Ce-sECP",
            },
            {
                "scalar_file": str(fast),
                "timestep": 0.05,
                "nonlocalmoves": True,
                "potential_label": "Ce-ONCV",
            },
        ],
        discard_fraction=0,
        reblock_count=2,
    )

    assert parsed["fits"]["tmove"] == {
        "status": "not_fit",
        "reason": "runs declare multiple potential_label values",
        "point_count": 2,
    }


def test_inspect_dmc_population_reports_retained_walker_measurements(tmp_path):
    path = tmp_path / "O.s001.dmc.dat"
    path.write_text("""\
# Population record
# Index LocalEnergy NumOfWalkers DiffEff LivingFraction
0 -10.0 100 0.80 0.95
2 -10.2 110 0.75 0.90
1 -10.1 90 0.85 1.00
# population-control comment
bad row
1.5 -10.1 90 0.85 1.00
""", encoding="utf-8")

    parsed = inspect_dmc_population(
        path,
        target_walkers=100,
        discard_fraction=1 / 3,
    )

    assert parsed == {
        "schema_version": "chemtools.qmcpack-dmc-population/1",
        "path": str(path.resolve()),
        "columns": [
            "Index", "LocalEnergy", "NumOfWalkers", "DiffEff", "LivingFraction",
        ],
        "row_count": 3,
        "invalid_row_count": 2,
        "invalid_row_reasons": {
            "malformed": 1,
            "non_finite": 0,
            "non_integral_index": 1,
        },
        "truncated": False,
        "block_index_sequence": {
            "status": "noncontiguous",
            "gap_transition_count": 1,
            "nonincreasing_transition_count": 1,
        },
        "warnings": [
            "The DMC population file excluded 1 malformed row(s).",
            "The DMC population file excluded 1 non-integral-index row(s).",
            "The DMC population file has gaps or nonincreasing block indices.",
        ],
        "discard_fraction": 1 / 3,
        "discarded_block_count": 1,
        "retained_block_count": 2,
        "walkers": {
            "mean": 100.0,
            "sample_stdev": pytest.approx(14.142135623730951),
            "minimum": 90.0,
            "maximum": 110.0,
            "last": 90.0,
            "target_walkers": 100,
            "mean_relative_deviation": 0.0,
            "last_relative_deviation": -0.1,
        },
        "living_fraction": {
            "mean": 0.95,
            "sample_stdev": pytest.approx(0.07071067811865474),
            "minimum": 0.9,
            "maximum": 1.0,
            "last": 1.0,
        },
        "diffusion_efficiency": {
            "mean": 0.8,
            "sample_stdev": pytest.approx(0.07071067811865474),
            "minimum": 0.75,
            "maximum": 0.85,
            "last": 0.85,
        },
    }
    assert _handle_inspect_qmcpack_dmc_population({
        "dmc_file": str(path),
        "target_walkers": 100,
        "discard_fraction": 1 / 3,
    }) == parsed


def test_inspect_dmc_population_identifies_nonfinite_only_rows(tmp_path):
    path = tmp_path / "O.s001.dmc.dat"
    path.write_text("""\
# Index NumOfWalkers DiffEff LivingFraction
0 20 -nan 1.0
""", encoding="utf-8")

    with pytest.raises(
        ValueError,
        match=r"contains no valid block rows\. Rejected: 1 non-finite row\(s\)\.",
    ):
        inspect_dmc_population(path)


def test_inspect_dmc_population_reports_nonfinite_rows_with_valid_data(tmp_path):
    path = tmp_path / "O.s001.dmc.dat"
    path.write_text("""\
# Index NumOfWalkers DiffEff LivingFraction
0 20 -nan 1.0
1 22 0.8 0.9
""", encoding="utf-8")

    inspected = inspect_dmc_population(path, discard_fraction=0)

    assert inspected["invalid_row_reasons"] == {
        "malformed": 0,
        "non_finite": 1,
        "non_integral_index": 0,
    }
    assert inspected["warnings"] == [
        "The DMC population file excluded 1 non-finite row(s)."
    ]


def test_inspect_dmc_population_from_input_binds_walker_target(tmp_path):
    input_path = tmp_path / "campaign.xml"
    input_path.write_text("""\
<simulation>
  <qmc method="dmc">
    <parameter name="total_walkers">120</parameter>
  </qmc>
</simulation>
""", encoding="utf-8")
    population_path = tmp_path / "Ce.s001.dmc.dat"
    population_path.write_text("""\
# Index NumOfWalkers LivingFraction
0 114 0.95
1 126 0.96
""", encoding="utf-8")
    arguments = {
        "qmcpack_input": str(input_path),
        "dmc_file": str(population_path),
        "qmc_block_index": 0,
        "discard_fraction": 0,
    }

    inspected = inspect_dmc_population_from_input(**arguments)

    assert inspected["schema_version"] == "chemtools.qmcpack-dmc-population-input/1"
    assert inspected["dmc_input"]["target_walkers"] == 120
    assert inspected["population"]["walkers"] == {
        "mean": 120.0,
        "sample_stdev": pytest.approx(8.48528137423857),
        "minimum": 114.0,
        "maximum": 126.0,
        "last": 126.0,
        "target_walkers": 120,
        "mean_relative_deviation": 0.0,
        "last_relative_deviation": 0.05,
    }
    assert _handle_inspect_qmcpack_dmc_population_from_input(arguments) == inspected

    with pytest.raises(ValueError, match="does not select a DMC block"):
        inspect_dmc_population_from_input(input_path, population_path, 1)


def test_check_vmc_energy_gate_compares_matching_hartree_energies(tmp_path):
    path = tmp_path / "O.vmc.scalar.dat"
    path.write_text(
        "# index LocalEnergy\n0 -10.1\n1 -10.3\n2 -10.5\n",
        encoding="utf-8",
    )

    passed = check_vmc_energy_gate(
        str(path),
        trial_scf_energy_hartree=-10.2,
        discard_fraction=1 / 3,
    )

    assert passed == {
        "schema_version": "chemtools.qmcpack-vmc-energy-gate/1",
        "scalar_file": str(path.resolve()),
        "source_block_count": 3,
        "discard_fraction": 1 / 3,
        "discarded_block_count": 1,
        "retained_block_count": 2,
        "vmc_energy_hartree": -10.4,
        "trial_scf_energy_hartree": -10.2,
        "vmc_minus_trial_hartree": -0.20000000000000107,
        "gate": {
            "status": "passed",
            "criterion": "VMC LocalEnergy <= trial SCF energy",
        },
        "invalid_row_count": 0,
        "invalid_row_reasons": {
            "malformed": 0,
            "non_finite": 0,
            "non_integral_index": 0,
        },
        "local_energy_second_moment": {
            "status": "not_available",
            "reason": "LocalEnergy and LocalEnergy_sq columns are required.",
        },
        "acceptance_ratio_bounds": {
            "status": "not_available",
            "reason": "An AcceptRatio column is required.",
        },
        "block_weight_quality": {
            "status": "not_available",
            "reason": "A BlockWeight column is required.",
        },
        "energy_component_balance": {
            "status": "not_available",
            "reason": "LocalEnergy, Kinetic, and LocalPotential columns are required.",
        },
        "truncated": False,
        "block_index_sequence": {
            "status": "contiguous",
            "gap_transition_count": 0,
            "nonincreasing_transition_count": 0,
        },
        "warnings": [],
        "statistical_limit": (
            "This comparison uses the retained scalar-block mean without "
            "autocorrelation or reblocking analysis."
        ),
    }
    failed = _handle_check_qmcpack_vmc_energy_gate({
        "scalar_file": str(path),
        "trial_scf_energy_hartree": -10.6,
    })
    assert failed["gate"]["status"] == "failed"


def test_vmc_energy_gate_preserves_nonfinite_scalar_evidence(tmp_path):
    path = tmp_path / "O.vmc.scalar.dat"
    path.write_text(
        "# index LocalEnergy\n0 nan\n1 -10.3\n2 -10.5\n",
        encoding="utf-8",
    )

    inspected = check_vmc_energy_gate(
        str(path),
        trial_scf_energy_hartree=-10.2,
    )

    assert inspected["invalid_row_reasons"] == {
        "malformed": 0,
        "non_finite": 1,
        "non_integral_index": 0,
    }
    assert inspected["warnings"] == [
        "At least one scalar file contains non-finite rows that were excluded.",
    ]


def test_vmc_energy_gate_warns_about_inconsistent_local_energy_second_moment(tmp_path):
    path = tmp_path / "O.vmc.scalar.dat"
    path.write_text(
        "# index LocalEnergy LocalEnergy_sq\n0 -10.0 99\n1 -10.2 105\n",
        encoding="utf-8",
    )

    inspected = check_vmc_energy_gate(
        str(path),
        trial_scf_energy_hartree=-10.0,
    )

    assert inspected["local_energy_second_moment"]["status"] == "inconsistent"
    assert inspected["warnings"] == [
        "At least one scalar file has LocalEnergy_sq below the LocalEnergy "
        "second-moment bound."
    ]


def test_vmc_energy_gate_warns_about_out_of_bounds_acceptance_ratio(tmp_path):
    path = tmp_path / "O.vmc.scalar.dat"
    path.write_text(
        "# index LocalEnergy AcceptRatio\n0 -10.0 -0.01\n1 -10.2 0.9\n",
        encoding="utf-8",
    )

    inspected = check_vmc_energy_gate(
        str(path),
        trial_scf_energy_hartree=-10.0,
    )

    assert inspected["acceptance_ratio_bounds"]["status"] == "out_of_bounds"
    assert inspected["warnings"] == [
        "At least one scalar file has AcceptRatio values outside [0, 1]."
    ]


def test_vmc_energy_gate_warns_about_nonpositive_block_weight(tmp_path):
    path = tmp_path / "O.vmc.scalar.dat"
    path.write_text(
        "# index LocalEnergy BlockWeight\n0 -10.0 -1\n1 -10.2 1\n",
        encoding="utf-8",
    )

    inspected = check_vmc_energy_gate(
        str(path),
        trial_scf_energy_hartree=-10.0,
    )

    assert inspected["block_weight_quality"]["status"] == "nonpositive"
    assert inspected["warnings"] == [
        "At least one scalar file has non-positive BlockWeight values; its "
        "weighted LocalEnergy mean is unavailable."
    ]


def test_vmc_energy_gate_warns_about_unbalanced_energy_components(tmp_path):
    path = tmp_path / "O.vmc.scalar.dat"
    path.write_text(
        "# index LocalEnergy Kinetic LocalPotential\n0 -10.0 2 -12\n1 -10.2 2 -12\n",
        encoding="utf-8",
    )

    inspected = check_vmc_energy_gate(
        str(path),
        trial_scf_energy_hartree=-10.0,
    )

    assert inspected["energy_component_balance"]["status"] == "unbalanced"
    assert inspected["warnings"] == [
        "At least one scalar file has an unbalanced LocalEnergy, Kinetic, "
        "and LocalPotential record."
    ]


def test_determinant_only_vmc_offsets_preserve_positive_state_ordered_evidence(tmp_path):
    scalar_files = []
    for state, energy in (("neutral", -9.0), ("3+", -19.0), ("4+", -29.0)):
        path = tmp_path / f"Ce-{state}.vmc.scalar.dat"
        path.write_text(
            (
                f"# index LocalEnergy\n0 {energy}\n2 {energy}\nbad row\n"
                if state == "neutral"
                else f"# index LocalEnergy\n0 {energy}\n1 {energy}\n"
            ),
            encoding="utf-8",
        )
        scalar_files.append((state, path))

    runs = [
        {
            "state_label": "neutral",
            "scalar_file": str(scalar_files[0][1]),
            "trial_scf_energy_hartree": -10.0,
        },
        {
            "state_label": "3+",
            "scalar_file": str(scalar_files[1][1]),
            "trial_scf_energy_hartree": -19.5,
        },
        {
            "state_label": "4+",
            "scalar_file": str(scalar_files[2][1]),
            "trial_scf_energy_hartree": -29.25,
        },
    ]

    inspected = inspect_determinant_only_vmc_offsets(runs)

    assert inspected["all_vmc_minus_trial_offsets_positive"] is True
    assert inspected["offset_trend_in_supplied_state_order"] == "strictly_decreasing"
    assert [point["vmc_minus_trial_hartree"] for point in inspected["points"]] == [
        1.0,
        0.5,
        0.25,
    ]
    assert inspected["warnings"] == [
        "At least one scalar file contains malformed rows that were excluded.",
        "At least one scalar file has gaps or nonincreasing block indices.",
    ]
    assert _handle_inspect_qmcpack_determinant_vmc_offsets({"runs": runs}) == inspected


def test_compare_tmove_locality_shift_requires_matched_timestep(tmp_path):
    tmove = tmp_path / "tmove.scalar.dat"
    no_tmove = tmp_path / "no-tmove.scalar.dat"
    tmove.write_text(
        "# index LocalEnergy\n0 -10.1\n1 -9.9\n2 -9.9\n3 -9.7\n",
        encoding="utf-8",
    )
    no_tmove.write_text(
        "# index LocalEnergy\n0 -10.0\n1 -9.8\n2 -9.8\n3 -9.6\nbad row\n",
        encoding="utf-8",
    )
    arguments = {
        "tmove": {
            "scalar_file": str(tmove),
            "timestep": 0.01,
            "target_walkers": 100,
            "potential_label": "Ce-sECP",
        },
        "no_tmove": {
            "scalar_file": str(no_tmove),
            "timestep": 0.01,
            "target_walkers": 100,
            "potential_label": "Ce-sECP",
        },
        "discard_fraction": 0,
        "reblock_count": 2,
    }

    compared = compare_tmove_locality_shift(**arguments)

    assert compared["no_tmove_minus_tmove_hartree"] == pytest.approx(0.1)
    assert compared["standard_error_hartree"] == pytest.approx(0.141421356237309)
    assert compared["walker_count_comparability"] == {
        "status": "matched",
        "target_walkers": 100,
    }
    assert compared["potential_identity"] == {
        "status": "matched",
        "potential_label": "Ce-sECP",
    }
    assert compared["warnings"] == [
        "At least one scalar file contains malformed rows that were excluded."
    ]
    assert _handle_compare_qmcpack_tmove_locality_shift(arguments) == compared
    unlabeled_tmove = {
        key: value
        for key, value in arguments["tmove"].items()
        if key != "potential_label"
    }
    unlabeled_no_tmove = {
        key: value
        for key, value in arguments["no_tmove"].items()
        if key != "potential_label"
    }
    unlabeled = compare_tmove_locality_shift(
        unlabeled_tmove,
        unlabeled_no_tmove,
        discard_fraction=0,
        reblock_count=2,
    )
    assert unlabeled["potential_identity"] == {
        "status": "not_assessed",
        "reason": "potential_label was not supplied for both matched runs",
    }
    with pytest.raises(ValueError, match="matching timesteps"):
        compare_tmove_locality_shift(
            arguments["tmove"],
            {**arguments["no_tmove"], "timestep": 0.02},
        )
    with pytest.raises(ValueError, match="matching potential_label"):
        compare_tmove_locality_shift(
            arguments["tmove"],
            {**arguments["no_tmove"], "potential_label": "Ce-ONCV"},
        )


def test_compare_tmove_locality_shift_from_input_binds_selected_controls(tmp_path):
    input_path = tmp_path / "campaign.xml"
    input_path.write_text("""\
<simulation>
  <qmc method="dmc">
    <parameter name="timestep">0.01</parameter>
    <parameter name="nonlocalmoves">yes</parameter>
    <parameter name="targetWalkers">100</parameter>
  </qmc>
  <qmc method="dmc">
    <parameter name="timestep">0.01</parameter>
    <parameter name="nonlocalmoves">no</parameter>
    <parameter name="total_walkers">100</parameter>
  </qmc>
</simulation>
""", encoding="utf-8")
    tmove = tmp_path / "tmove.scalar.dat"
    no_tmove = tmp_path / "no-tmove.scalar.dat"
    tmove.write_text("# index LocalEnergy\n0 -10.1\n1 -9.9\n", encoding="utf-8")
    no_tmove.write_text("# index LocalEnergy\n0 -10.0\n1 -9.8\n", encoding="utf-8")
    arguments = {
        "qmcpack_input": str(input_path),
        "tmove": {
            "scalar_file": str(tmove),
            "qmc_block_index": 0,
            "potential_label": "Ce-sECP",
        },
        "no_tmove": {
            "scalar_file": str(no_tmove),
            "qmc_block_index": 1,
            "potential_label": "Ce-sECP",
        },
        "discard_fraction": 0,
        "reblock_count": 2,
    }

    compared = compare_tmove_locality_shift_from_input(**arguments)

    assert compared["schema_version"] == "chemtools.qmcpack-tmove-locality-shift-input/1"
    assert compared["tmove_binding"]["dmc_input"]["nonlocalmoves"] is True
    assert compared["no_tmove_binding"]["dmc_input"]["nonlocalmoves"] is False
    assert compared["comparison"]["timestep"] == 0.01
    assert compared["comparison"]["walker_count_comparability"] == {
        "status": "matched",
        "target_walkers": 100,
    }
    assert _handle_compare_qmcpack_tmove_locality_shift_from_input(arguments) == compared

    with pytest.raises(ValueError, match="tmove must select"):
        compare_tmove_locality_shift_from_input(
            input_path,
            arguments["no_tmove"],
            arguments["tmove"],
        )
