"""DIRAC ``.mol`` (geometry + basis) drafter.

Renders a `.mol` file from a structured spec:

    atoms     — list of {label, x, y, z, [nuclear_charge or element]}
    basis     — per-element basis: {"H": "cc-pVDZ", "O": "cc-pVDZ"} or per Z
    units     — "bohr" (default) or "angstrom"
    title     — human-readable title (up to 2 lines)
    symmetry  — "auto" (let DIRAC detect), "C1" (no symmetry), or list of
                generators from {"X", "Y", "Z"}

The output follows DIRAC's positional format (see programs/dirac/parse/mol.py
for the parser's view of the same format).
"""

from __future__ import annotations

from typing import Any

from chemtools.core.common import ATOMIC_SYMBOLS, ELEMENT_TO_Z


def draft_mol(
    atoms: list[dict[str, Any]],
    *,
    basis: dict[str, str] | dict[int, str] | None = None,
    units: str = "bohr",
    title: str = "DIRAC mol file generated by chemtools",
    title_line2: str = "",
    symmetry: str | list[str] = "auto",
    default_basis: str | None = None,
) -> str:
    """Render a DIRAC ``.mol`` file from atoms + per-element basis.

    Returns the file text. Caller writes to disk.

    Parameters
    ----------
    atoms
        List of dicts. Each must have ``label`` (atom label or symbol),
        ``x``, ``y``, ``z`` (coordinates). Optionally
        ``nuclear_charge`` or ``element`` to disambiguate the Z when the
        label doesn't match a real element symbol (e.g. ``N1``).
    basis
        Mapping. Either ``{element_symbol: basis_name}`` or
        ``{nuclear_charge: basis_name}``. Falls back to ``default_basis``
        if an element isn't in the dict. Caller is responsible for
        knowing the available basis names (dyall.v2z, cc-pVDZ, etc.).
    units
        "bohr" (default — no ``A`` flag in header) or "angstrom"
        (adds ``A`` to the coord header).
    symmetry
        "auto" (DIRAC will detect), "C1" (explicit no-symmetry —
        ``C   N   0``), or a list of generators e.g. ``["Y", "Z"]``
        for C2v with Y and Z generators.
    """
    if not atoms:
        raise ValueError("draft_mol: atoms list is empty.")

    # Group atoms by nuclear charge (DIRAC atomtype = "all atoms with the
    # same Z and basis").
    by_z: dict[int, list[dict[str, Any]]] = {}
    for a in atoms:
        z = _atom_to_z(a)
        if z is None:
            raise ValueError(f"Could not resolve nuclear charge for atom {a}")
        by_z.setdefault(z, []).append(a)

    # Resolve basis assignments per atomtype
    def _basis_for(z: int) -> str:
        if basis:
            if z in basis:
                return basis[z]
            sym = ATOMIC_SYMBOLS.get(z)
            if sym and sym in basis:
                return basis[sym]
        if default_basis:
            return default_basis
        raise ValueError(
            f"No basis assignment for Z={z}. Pass `basis={{'{ATOMIC_SYMBOLS.get(z, str(z))}': '...'}}` "
            f"or `default_basis='...'`."
        )

    # Build the C header line
    n_types = len(by_z)
    if symmetry == "C1":
        sym_part = "    0"
    elif symmetry == "auto":
        sym_part = ""  # blank = DIRAC's "use the natural symmetry" default
    else:
        # Explicit list of generators
        gens = symmetry if isinstance(symmetry, list) else [symmetry]
        n_gens = len(gens)
        sym_part = f"   {n_gens} " + " ".join(gens)

    units_flag = " A" if units.lower().startswith("angs") else ""
    header_line = f"C   {n_types}{sym_part}{units_flag}"

    # Magic header determines DIRAC's basis-read mode:
    #   INTGRL  → expects inline primitive exponents + contraction coefs
    #   DIRAC   → expects LARGE BASIS <name> library lookups
    # The drafter emits library lookups, so DIRAC is the right magic.
    lines: list[str] = [
        "DIRAC",
        title.strip() or "DIRAC mol",
        title_line2.strip() or "(generated)",
        header_line,
    ]

    for z in sorted(by_z.keys()):
        atype_atoms = by_z[z]
        n_atoms = len(atype_atoms)
        # DIRAC's atomtype header is right-aligned in a 10-column field for
        # Z followed by a 5-column field for the atom count (e.g.
        # ``       41.    1`` for Nb with one atom). Hardcoding 8 leading
        # spaces breaks for Z≥100 and even for Z=10..99 when combined with
        # certain readers — right-aligning matches what working fixtures use.
        z_str = f"{z}."
        lines.append(f"{z_str:>10s}{n_atoms:>5d}")
        for a in atype_atoms:
            label = a.get("label") or ATOMIC_SYMBOLS.get(z) or str(z)
            x = float(a["x"])
            y = float(a["y"])
            z_coord = float(a["z"])
            lines.append(f"{label:<8s}{x:18.10f}{y:18.10f}{z_coord:18.10f}")
        lines.append(f"LARGE BASIS {_basis_for(z)}")

    lines.append("FINISH")
    return "\n".join(lines) + "\n"


def _atom_to_z(atom: dict[str, Any]) -> int | None:
    """Resolve nuclear charge from an atom spec — checks ``nuclear_charge``,
    then ``element``, then the label."""
    if "nuclear_charge" in atom and atom["nuclear_charge"] is not None:
        return int(round(float(atom["nuclear_charge"])))
    element = atom.get("element")
    if element:
        z = ELEMENT_TO_Z.get(_titlecase(element))
        if z:
            return z
    label = atom.get("label", "")
    # Strip trailing digits from labels like ``N1``, ``H2`` and look up
    sym = "".join(c for c in label if c.isalpha())
    if sym:
        z = ELEMENT_TO_Z.get(_titlecase(sym))
        if z:
            return z
    return None


def _titlecase(s: str) -> str:
    return s[:1].upper() + s[1:].lower() if s else s
